import {
  Banknote,
  BarChart3,
  BrickWall,
  Cake,
  Calculator,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  Car,

  Coins,
  Container,
  Divide,
  Droplets,
  Dumbbell,
  Fuel,
  Gauge,
  Globe2,
  Grid3x3,
  HandCoins,
  HeartPulse,
  Hash,
  Landmark,
  Layers,
  LineChart,
  Map,
  Megaphone,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PawPrint,
  Percent,
  PiggyBank,
  PlugZap,
  Receipt,
  Ruler,
  Salad,
  Scale,
  Shapes,
  Sigma,
  Split,
  SquareRadical,
  Sun,
  Tag,
  Target,
  Thermometer,
  Timer,
  TrendingDown,
  TrendingUp,
  Truck,
  Wallet,
  Weight,
  Box,
  Flame,
  UtensilsCrossed,
  FileSignature,
  Briefcase,
  type LucideIcon,
} from "lucide-react";
import { categoryIcons } from "./category-icons";

/** Ikona dla każdego kalkulatora — kafle mają być rozpoznawalne bez czytania. */
const icons: Record<string, LucideIcon> = {
  procenty: Percent,
  vat: Receipt,
  rabat: Tag,
  marza: TrendingUp,
  "brutto-netto": Wallet,
  bmi: Scale,
  bmr: Flame,
  "spalanie-paliwa": Fuel,
  wiek: Cake,
  "raty-kredytu": Landmark,
  "lokata-procent-skladany": PiggyBank,
  inflacja: TrendingDown,
  "odsetki-ustawowe": FileSignature,
  "amortyzacja-srodka-trwalego": LineChart,
  leasing: Truck,
  "wynagrodzenie-netto-brutto": Banknote,
  "emerytura-orientacyjna": HandCoins,
  "nwd-nww": Divide,
  "silnia-kombinatoryka": Sigma,
  "pierwiastki-potegi": SquareRadical,
  "system-liczbowy": Hash,
  "pole-obwod-figur": Shapes,
  "objetosc-bryl": Box,
  tdee: Dumbbell,
  makroskladniki: Salad,
  "zapotrzebowanie-na-wode": Droplets,
  "tetno-treningowe": HeartPulse,
  "wiek-psa-kota": PawPrint,
  "waga-idealna": Target,
  "tempo-biegowe": Timer,
  "powierzchnia-malowania": PaintRoller,
  "zuzycie-farby": PaintBucket,
  "ilosc-plytek": Grid3x3,
  "kubatura-betonu": Container,
  "zuzycie-tapet": Paintbrush,
  "liczba-cegiel": BrickWall,
  "zuzycie-energii-urzadzen": PlugZap,
  "oplacalnosc-fotowoltaiki": Sun,
  "koszt-podrozy": Map,
  "przyspieszenie-predkosc": Gauge,
  "zuzycie-paliwa-trasa": Car,
  "roznica-dni": CalendarRange,
  "dodawanie-dni": CalendarPlus,
  "dni-robocze": CalendarDays,
  "wiek-emerytalny": Briefcase,
  "strefy-czasowe": Globe2,
  dlugosc: Ruler,
  waga: Weight,
  objetosc: Layers,
  powierzchnia: Grid3x3,
  predkosc: Gauge,
  cisnienie: Gauge,
  temperatura: Thermometer,
  "waluta-manualna": Coins,
  cpm: Megaphone,
  roas: BarChart3,
  roi: TrendingUp,
  "prog-rentownosci": Split,
  napiwek: UtensilsCrossed,
  "split-bill": Split,
};

export function getCalculatorIcon(slug: string, category?: string): LucideIcon {
  return icons[slug] ?? (category ? categoryIcons[category] : undefined) ?? Calculator;
}


